from pathlib import Path

ROOT = Path(__file__).parent
ASSETS = ROOT / 'assets'
IMAGES_ASSETS = ASSETS / 'images'
WINDOW_ICON = IMAGES_ASSETS / 'lrc_black.png'

# Colors
PRIMARY_COLOR = '#1e81b0'
DARKER_PRIMARY_COLOR = '#16658a'
DARKEST_PRIMARY_COLOR = '#115270'

# Style
BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 24
SMALL_FONT_SIZE = 18

TEXT_MARGIN = 15
MINIMUN_WIDTH = 500